name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup Volta
        uses: volta-cli/action@v1
        with:
          node-version: '22.14.0'
          yarn-version: '4.0.0'

      - name: Install Dependencies
        working-directory: js
        run: yarn install

      - name: Build
        working-directory: js
        run: yarn build

      - name: Lint
        working-directory: js
        run: yarn lint

      - name: Test
        working-directory: js
        run: yarn test
