name: Build, Test and Publish

on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    branches: [main]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Volta
        uses: volta-cli/action@v1
        with:
          node-version: '22.14.0'
          yarn-version: '4.0.0'

      - name: Install Dependencies
        working-directory: js
        run: yarn install

      - name: Build
        working-directory: js
        run: yarn build

      - name: Lint
        working-directory: js
        run: yarn lint

      - name: Test
        working-directory: js
        run: yarn test

      - name: Publish to NPM
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        working-directory: js
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          yarn publish-release
          yarn update-examples
          # commit changes
          git config --global user.email "lixun910@gmail.com"
          git config --global user.name "github-actions[bot]"
          cd ..
          git add .
          git commit -m "Update examples to version ${GITHUB_REF_NAME}"
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
